meta_product_name: "Ife Odugbesan"
meta_title: "Ife Odugbesan - Full Stack Developer"
meta_description: "Find out more about me, the technologies I use and the projects I've built."
meta_image: "cover.png" # should exist in `app/assets/images/`
